name: CD Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Render Production Deploy Hook
      if: env.RENDER_DEPLOY_HOOK_URL != ''
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl -X GET "$RENDER_DEPLOY_HOOK_URL"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      if: env.VERCEL_TOKEN != ''
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

    - name: Build Project Artifacts
      if: env.VERCEL_TOKEN != ''
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel build --prod --token=$VERCEL_TOKEN

    - name: Deploy Project Artifacts to Vercel
      if: env.VERCEL_TOKEN != ''
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
